[package]
name = "typing-test"
version = "0.1.0"
authors = ["Jason Holm <holmjason2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap = "0.11"
difference = "2.0"
